apiVersion: v1
kind: Namespace
metadata:
  name: integration-test-utils
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: trustacks-controller
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: trustacks-controller
subjects:
- kind: ServiceAccount
  name: trustacks-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: trustacks-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: trustacks-controller