apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: docker
        image: docker:20.10.22-dind
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        ports:
        - containerPort: 2375
        securityContext:
          privileged: true
        args: 
        - --mtu=1450