---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ts-temporal-worker
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ts-temporal-worker
subjects:
- kind: ServiceAccount
  name: ts-temporal-worker
  namespace: default
roleRef:
  kind: ClusterRole
  name: ts-temporal-worker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ts-temporal-worker