name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Run Unit Test
        run: go test ./... -v -race

  lint:
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=3m