name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Run Unit Test
        run: go test ./... -v -race

  firebase_test:
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Firebase Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup java
        uses: actions/setup-java@v3
        with: 
          distribution: 'zulu'
          java-version: "11"
      - name: Setup firebase tools
        run: curl -sL firebase.tools | bash
      - name: Run firebase integration tests
        run: firebase emulators:exec --only firestore --project fake-project-id 'go test ./... -v -race -tags=test_firebase'

  lint:
    if: "!startsWith(github.event.head_commit.message, 'docs')"
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout=3m